version: "2"
services:
  app:
    image: nasajon/ionic:android-sdk-ubuntu
    command: yarn run start
    privileged: true
    restart: always    
    depends_on:
      - install
    working_dir: /build
    ports:
      - 3333:3333
      - 8100:8100
      - 8000:8000
      - 35729:35729
      - 53703:53703    
    volumes:
      - ./:/build
      - /dev/bus/usb:/dev/bus/usb      
    environment:
      - HTTP_PROXY=$HTTP_PROXY
      - HTTPS_PROXY=$HTTP_PROXY
  install:
    image: nasajon/ionic:android-sdk-ubuntu
    command: yarn install
    privileged: true    
    working_dir: /build
    user: '1002' #Colocar seu id de usuario. Rode $UID no terminal para descobrir.
    volumes:
      - ./:/build      
      - $SSH_AUTH_SOCK:/ssh-auth.sock 
      - /etc/passwd:/etc/passwd:ro 
      - /etc/group:/etc/group:ro 
      - $HOME/.ssh:$HOME/.ssh 
    environment:
      - HTTP_PROXY=$HTTP_PROXY
      - HTTPS_PROXY=$HTTP_PROXY  